### ISSUE TITLE
cannot connect?

### ISSUE THREAD

**Issue by matrixreal** [benVigie/Birds#4]
Hi,
great project i really like it 
i did exactly what you say in the tutorial
i got this problem
any help
![flappyerror](https://cloud.githubusercontent.com/assets/6823974/26675828/a211302c-46c5-11e7-9597-52c4c67859dd.jpg)

**Comment by benVigie** [comment]
OK, I just clone this old project and found the error.

In `sharedConstants.js`, I let an old IP address hardcoded, my bad 😞 
To play locally, replace the `SOCKET_ADDR` by `localhost`:

```
var constant = {

  SERVER_PORT:              4242,
  SOCKET_PORT:              1337,
  // SOCKET_ADDR:              'http://192.168.1.76',
  SOCKET_ADDR:              'http://localhost',
```
If you want to play with friends on different PC, set the server IP in `SOCKET_ADDR`.

Have fun ! Now I will make few games too 😆  ...

**Comment by matrixreal** [comment]
@benVigie 
thanks a lot :D thats work pretty good but the game is hard wow
i want to see the sunset effect 🗡

**Comment by benVigie** [comment]
HA HA HA, good luck, I'm barely reach 15 now :stuck_out_tongue_closed_eyes: !
